src/Entity/Song.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SongRepository")
 */
class Song
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $song_url;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Album", inversedBy="songs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $album;

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return Song
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getSongUrl(): ?string
    {
        return $this->song_url;
    }

    /**
     * @param string $song_url
     * @return Song
     */
    public function setSongUrl(string $song_url): self
    {
        $this->song_url = $song_url;

        return $this;
    }

    /**
     * @return Album|null
     */
    public function getAlbum(): ?Album
    {
        return $this->album;
    }

    /**
     * @param Album|null $album
     * @return Song
     */
    public function setAlbum(?Album $album): self
    {
        $this->album = $album;

        return $this;
    }


}

src/Form/SongType.php
<?php

namespace App\Form;

use App\Entity\Song;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SongType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', null,
                array(
                    'label' => false,
                    'attr' => array(
                        'placeholder' => 'Enter song name',
            )))
            ->add('song_url', null,
                array(
                    'label' => false,
                    'attr' => array(
                        'placeholder' => 'https://soundcloud.com/...',
            )))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Song::class,

        ]);
    }
}

src/Controller/SongController.php
<?php

namespace App\Controller;

use App\Entity\Song;
use App\Entity\Album;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/song")
 */
class SongController extends AbstractController
{
    /**
     * @Route("/{id}/{album}", name="song_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Song $song, Album $album): Response
    {
        if ($this->isCsrfTokenValid('delete'.$song->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($song);
            $entityManager->flush();
        }
        $this->addFlash('song', 'Song was deleted.');
        return $this->redirectToRoute('album_show', ['id' => $album->getId()]);
    }
}

templates/song/_delete_form.html.twig
<form method="post" action="{{ path('song_delete', {'id': song.id, 'album': album.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ song.id) }}">
    <button class="btn btn-danger btn-sm">Delete</button>
</form>

templates/song/_form.html.twig
{{ form_start(formSong, {'attr': {'class': 'form-inline'}}) }}

<div class="form-group mb-2">
            {{ form_row(formSong.name, { 'attr': {'class': 'form-control'} }) }}
        </div>
<div class="form-group mx-sm-3 mb-2">
            {{ form_row(formSong.song_url, { 'attr': {'class': 'form-control'} }) }}
        </div>

<button class="btn btn-primary mb-2">{{ button_label|default('Add song') }}</button>
{{ form_end(formSong) }}
<small style="color: black;">Please enter URL from <a href="https://www.soundcloud.com">SoundCloud</a>.</small>

templates/song/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Song{% endblock %}

{% block body %}
    <h1>Edit Song</h1>

    {{ include('song/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('song_index') }}">back to list</a>

    {{ include('song/_delete_form.html.twig') }}
{% endblock %}

templates/song/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Song index{% endblock %}

{% block body %}
    <h1>Song index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Song_url</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for song in songs %}
            <tr>
                <td>{{ song.id }}</td>
                <td>{{ song.name }}</td>
                <td>{{ song.songUrl }}</td>
                <td>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/song/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Song{% endblock %}

{% block body %}
    <h1>Create new Song</h1>

    {{ include('song/_form.html.twig') }}

    <a href="{{ path('song_index') }}">back to list</a>
{% endblock %}

templates/song/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Song{% endblock %}

{% block body %}
    <h1>Song</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ song.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ song.name }}</td>
            </tr>
            <tr>
                <th>Song_url</th>
                <td>{{ song.songUrl }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('song_index') }}">back to list</a>

    <a href="{{ path('song_edit', {'id': song.id}) }}">edit</a>

    {{ include('song/_delete_form.html.twig') }}
{% endblock %}